server.port: 12000
management.server.port: 12001


spring:
  config:
    import:
      - "classpath:config/wahlrecht.yaml"
      - "optional:configserver:${CONFIGSERVER_SCHEME:http}://${CONFIGSERVER_HOST:configserver}:${CONFIGSERVER_PORT:8888}${CONFIGSERVER_PREFIX:/config}"
