server:
  port: 8080
  shutdown: graceful

### technical configurations ###
management:
  # for security, don't use same port as application
  server.port: 8081
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint:
    health:
      show-details: always
      probes.enabled: true
      group:
        readiness.include: readinessState,diskSpace,grpcChannel,grpc,rest
        liveness.include: livenessState
  endpoints.web.exposure.include: '*'
  # activate percentiles for web and grpc requests
  metrics.distribution.percentiles-histogram:
    grpc.server.processing.duration: true
    http.server.requests: true

spring:
  main:
    banner-mode: off
  profiles:
    default: dev

# properties for application
de.twomartens.wahlrecht:
  defaultTimeZone: Europe/Berlin
  greeting: "Hello %s"

springdoc:
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    disable-swagger-default-url: true
    path: '/wahlrecht/v1/doc/'
  default-produces-media-type: 'application/json'
  api-docs:
    path: '/wahlrecht/v1/api-docs'

openapi:
  #TODO write description/ changelog
  description: |
    Open API Documentation for the Wahlrecht

    ## Header 2

    __YOUR TEXT HERE__

    ## Changelog

    |Version | Change                                 | Author | Date       |
    | ------ | -------------------------------------- | ------ | ---------- |
    | 1.0    | added API Versioning (and changelog)   | Jim    | 28.05.2023 |

  version: 1.0
  title: 'Wahlrecht API'

resttemplate:
  timeout:
    readTimeoutRestHealthIndicatorInMillis: 5000
    connectionRestHealthIndicatorTimeoutInMillis: 5000
    readTimeoutRestTemplateInMillis: 5000
    connectionRestTemplateTimeoutInMillis: 5000