de.twomartens.wahlrecht:
  defaultTimeZone: Europe/Berlin
  greeting: "Hello %s, on millenium"
  statusprobe:
    scheduleDuration: 60
    maxKafkaFailureDuration: 5
    maxBlobFailureCount: 5
    maxFailurePercent: 50