---
kind: pipeline
name: code quality
type: docker

platform:
  os: linux
  arch: arm64

clone:
  skip_verify: true

steps:
  - name: run code analysis
    pull: always
    image: 2martens/qodana-jvm-community-drone-plugin:2023.2
    settings:
      qodana_token:
        from_secret: qodana_token
      args: --baseline qodana.sarif.json --fail-threshold 0
    volumes:
      - name: cache
        path: /data/cache

volumes:
  - name: cache
    host:
      path: /var/lib/drone/cache

trigger:
  event:
    include:
      - push
      - pull_request
      - custom

---
kind: pipeline
name: build image
type: docker

platform:
  os: linux
  arch: arm64

clone:
  skip_verify: true

steps:
  - name: build Docker container
    image: gradle:8.2-jdk17
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    volumes:
      - name: cache
        path: /home/gradle/.gradle
    commands:
      - docker login -u $USERNAME -p $PASSWORD
      - ./gradlew jib

volumes:
  - name: cache
    host:
      path: /var/lib/drone/cache/.gradle

trigger:
  event:
    include:
      - push
      - custom

