kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

clone:
  skip_verify: true

steps:
  - name: restore-cache
    privileged: true
    pull: always
    image: 2martens/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./gradle
    volumes:
      - name: cache
        path: /cache
  - name: run code analysis
    pull: always
    image: 2martens/qodana-jvm-community-drone-plugin:2023.2
    settings:
      qodana_token:
        from_secret: qodana_token
      args: --baseline qodana.sarif.json --fail-threshold 0
  - name: rebuild-cache
    privileged: true
    image: 2martens/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./gradle
    volumes:
      - name: cache
        path: /cache

trigger:
  event:
    include:
      - push
      - pull_request

