kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

clone:
  skip_verify: true

steps:
  - name: run code analysis
    pull: always
    image: 2martens/qodana-jvm-community-drone-plugin:2023.2
    settings:
      qodana_token:
        from_secret: qodana_token
      args: --baseline qodana.sarif.json --fail-threshold 0
    volumes:
      - name: cache
        path: /data/cache

volumes:
  - name: cache
    host:
      path: /var/lib/drone/cache

trigger:
  event:
    include:
      - push
      - pull_request
      - custom

